_wandb:
    value:
        cli_version: 0.21.0
        e:
            qmhrnrn251bxza6ql6hui8z97v9xygfn:
                codePath: train_gamma.py
                codePathLocal: train_gamma.py
                cpu_count: 12
                cpu_count_logical: 24
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "1999701749760"
                        used: "928272560128"
                email: nagtamaghna@gmail.com
                executable: c:\Python313\python.exe
                gpu: NVIDIA GeForce RTX 4060 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 4352
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Ti
                      uuid: GPU-d1a48f26-44f9-1b15-c7a1-a7b4b567ef87
                host: Tamaghna
                memory:
                    total: "34278547456"
                os: Windows-10-10.0.19045-SP0
                program: c:\Users\Tamaghna\Documents\Insurance_GLM\train_gamma.py
                python: CPython 3.13.1
                root: c:\Users\Tamaghna\Documents\Insurance_GLM
                startedAt: "2025-07-25T12:59:40.047259Z"
                writerId: qmhrnrn251bxza6ql6hui8z97v9xygfn
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 5
                - 53
                - 105
            "2":
                - 5
                - 53
                - 105
            "3":
                - 2
                - 3
                - 13
            "4": 3.13.1
            "5": 0.21.0
            "8":
                - 1
                - 3
            "12": 0.21.0
            "13": windows-amd64
